### ISSUE TITLE
Relevanzranking

### ISSUE THREAD

**Issue by chantalw** [swissbib/vufind#214]
Hier sammle ich mal Beispiele, die ev. Hinweise zur Verbesserung des Relevanzrankings geben können.
1. Suchanfrage "glauser matto regiert" http://devbabe.swissbib.ch/Search/Results?lookfor=glauser+matto+regiert&type=AllFields: die erste Aufnahme des deutschsprachigen Originaltexts mit diesem Titel von Friedrich Glauser erscheint ziemlich weit unten in der Trefferliste. Auch nach Einschränken mit der Autorenfacette schafft es die neugriechische Übersetzung auf den ersten Platz, und auch andere Übersetzungen erscheinen vor dem deutschen Text.

**Comment by witzigs** [comment]
Suche nach Titel, der nur als Alternativtitel in Feld 246 erfasst ist. Beispiel (Aufnahme inzwischen angepasst):
Abfrage: Schweizer Archiv für Tierheilkunde 
Trefferliste: Aufnahmen mit Schweizer Archiv für Tierheilkunde in 245 $a erscheinen als erstes in der Trefferliste, Aufnahme mit Schweizer Archiv für Tierheilkunde in 246 $a und SAT in 245 $a erscheint erst auf Seite 2.

**Comment by sonjakupfi** [comment]
Mail von Florinne Egli, 25.11.2016:
"Ich habe eine Rückmeldung bekommen, die das Relevanzranking der Zeitschrift „Times Literary Supplement“ betrifft. Es wird als störend empfunden, dass die abgekürzte Titelform „TLS“ hinter Treffer wie „American literary criticism since the 1930s“ fällt."

Ausführlichere Erklärung:
Wenn mit "Times Literary Supplement" (in Suche mit und ohne "" getestet) über die einfache Suche eine Abfrage gemacht wird, werden diejenigen Objekte welche im Titel TLS haben und im Untertitel die ausgeschriebene Version, erst ab der 12. Stelle angezeigt (siehe 123722217 oder 373901445).
(baselbern.swissbib.ch)

Der Volltitel (titel_short) wird mit ^1000 im Ranking geboostet, alle weiteren Titelformen mit ^200.
Siehe searchspecs (https://github.com/swissbib/vufind/blob/master/local/config/vufind/searchspecs.yaml)

Die Relevanz wird zur Zeit nicht angepasst, da es zuerst eine systematische Zusammenstellung von "guten" und "weniger guten" Beispielen benötigt um die Reaktion auf die gesamten Objekte testen zu können.
Bitte Beispiele hier notieren.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Relevanzranking #214 (01/2015-wishful) Sammelissue!](https://trello.com/c/06Ijw194/97-relevanzranking-214-01-2015-wishful-sammelissue)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [214](https://trello.com/c/sfz04tHO/156-214)

**Comment by liowalter** [comment]
follow-up issue : https://github.com/swissbib/vufind/issues/684
I close this one because the first problem has been solved in the meantime
