### ISSUE TITLE
Autorensuche ergibt analoge Trefferliste (mit sämtlichen Facetten)

### ISSUE THREAD

**Issue by ToVie** [swissbib/vufind#32]
Ergebnis analog https://github.com/swissbib/sbvf2/issues/162

Exploration: Nochmals anschauen die drei Optionen gemäss https://github.com/swissbib/sbvf2/issues/162#issuecomment-27104890 
Fragen
* Geht z.B. die wikipedia-Funktion verloren? http://sb-vf20.swissbib.unibas.ch/vfrd/Author/Home?author=Meier%2C+Helen&type=Author
* Oder hat sich das Problem bereits gelöst, werden die Favoritenbibliotheken sowieso angezeigt)

**Comment by guenterh** [comment]
The implementation is easily be done with an additional template 
link-author.phtml in sbvfrd/templates/RecordDriver/SolrDefault/link-author.phtml

for an alternative to create the link look at the example in the code. 
Difficulties I have with ZF2 View Helper  is the URL encoding. I'm not sure if it is correct
something like Müller
(http://test.swissbib.ch/Record/010811443)
seems to be correct
Search/Results?lookfor=M%C3%BCller&type=Author

but a Authour like "Syngenta AG(Basel)" with brackets is implemented in another way by the native function urlencode
Search/Results?lookfor=Syngenta%20AG%20(Basel)&type=Author 
Syngenta+AG+%28Basel%29 (urlencode)

compare
http://stackoverflow.com/questions/996139/urlencode-vs-rawurlencode/996161#996161

At the moment I dont have enough time for this but we should try it with the URL View Helper

**Comment by guenterh** [comment]
The comment in the script was an error because the file is directly included by the parent file to build the link. Therefor here the comment I had in the script


related to the way I created the link

an alternative would be something like
 $this->url('search-results')?>?lookfor=%22 =urlencode($this->lookfor)?>%22&amp;type=Subject
the way it is done by VF2 (a little bit ugly). My Favorite is to use the functionality of the ZF2 URL view helper

In 2013 / 2014 I have found Google entries that URL Helper might have difficulties with the encoding, but I'm not sure
if this is correct

-->

**Comment by guenterh** [comment]
https://github.com/swissbib/vufind/commit/fd120a709addc166646732f9656dc021e4f8d2d8
