### ISSUE TITLE
Erweiterungen/Anpassungen nach merge mit MultiDomains in core 

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#340]
after merge of initial MultiDomain implementation in VF2 core we have to do some adaptations.
I started with
https://github.com/swissbib/vufind/commit/35b10c0133ff67d03cbd4b9b13bff3745c6b9d7a

what is still missing (first overview)
* [x] Solr\Results->getMyLibrariesFacets
* [ ] Handling of getFacetLists in Summon target
* [x] initializations in swissbib bootstrapper ok and compatible with VF
* [ ] former configuration of translations in swissbib module by now not compatible with new VF implementation

**Comment by edelm** [comment]
- didn't find any relevant place in getFacetsList
- what do we have to check in " former configuration of translations in swissbib module"? we checked if we still need the swissbib translator and run into un-translated institutions (institutions aren't in a text-domain by now. but vufind-mechanism would put them in an own domain because they're in a subfolder).

**Comment by guenterh** [comment]
vgl. Kommentare in https://github.com/swissbib/vufind/issues/346
dort geschlossen
