### ISSUE TITLE
no direct link in result list  when article is part of national licenses and some other repository

### ISSUE THREAD

**Issue by guenterh** [swissbib/vufind#469]
@liowalter @edelm 
If NL resources were merged together with resources from other repositories there is no direct link in the result list to NL (by intentiton?)
Examples
https://www.swissbib.ch/Search/Results?type=AllFields&filter%5B%5D=union%3A%22NATIONALLICENCE%22&filter%5B%5D=union%3A%22ZORA%22
https://www.swissbib.ch/Search/Results?type=AllFields&filter%5B%5D=union%3A%22NATIONALLICENCE%22&filter%5B%5D=union%3A%22BORIS%22

**Comment by liowalter** [comment]
Sometimes there is : 
https://www.swissbib.ch/Search/Results?lookfor=395256313&type=AllFields&limit=20&sort=relevance

**Comment by liowalter** [comment]
The fix hasn't solve the problem. Example : 
https://www.swissbib.ch/Search/Results?lookfor=Gender+differences+in+intergenerational+care+in+European+welfare+states&type=AllFields&filter%5B%5D=union%3A%22NATIONALLICENCE%22&filter%5B%5D=union%3A%22ZORA%22&limit=20&sort=relevance

I think the problem comes from that : 
https://github.com/swissbib/vufind/commit/ff6dfff0eb1096ba9c66c53965d87481960ffeaf

@edelm : can you take that over ?

**Comment by liowalter** [comment]
Ok now.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [no direct link in result list when article is part of national licenses and some other repository #469](https://trello.com/c/j33H02rh/36-no-direct-link-in-result-list-when-article-is-part-of-national-licenses-and-some-other-repository-469)
