### ISSUE TITLE
keep the global search field on result page even if advance filter is used

### ISSUE THREAD

**Issue by gagarine** [swissbib/vufind#504]
On the front page you have a big search field:
![screen shot 2017-04-11 at 16 49 08](https://cloud.githubusercontent.com/assets/164074/24915203/d9bd3ad2-1ed6-11e7-983f-e868107b62c6.png)

But after you search it disappear if you add some advance field (like filter a network):
![screen shot 2017-04-11 at 16 49 03](https://cloud.githubusercontent.com/assets/164074/24915206/e0d9a756-1ed6-11e7-80c7-a09fac2ff85f.png)

This doesn't make any sens. I aware I can click on "edit my search" but this is nor particle neither intuitive. I can think of one single search engine than do that.

This is what I want:
![screen shot 2017-04-11 at 16 51 43](https://cloud.githubusercontent.com/assets/164074/24915390/4aeff744-1ed7-11e7-8eea-141dd7e9366e.png)

**Comment by witzigs** [comment]
If you are using the advanced search the searchbox disappears and gives you the possibility to edit your advanced search which you wouldn't have otherwise. 
If you are using the simple search and filters on the right hand side of the result list the searchbox stays in place. 
This is standard behaviour of VuFind which we decided not to change.

**Comment by gagarine** [comment]
ok I will open this bug upstream.
