### ISSUE TITLE
Artikel und mehr in VF5 (Summon)

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#636]
Momentan funktioniert nicht:
* Suche absetzten in Artikel und mehr (Fehler Call to undefined method VuFind\Search\Summon\Results::getMyLibrariesFacets())
* Erweiterte Suche aufrufen (Fehler: Call to a member function getLimit() on null)

**Comment by liowalter** [comment]
Search now works, but display is bad (standard display rather than swissbib display)
cf . http://devbabe.swissbib.ch/Summon/Search?lookfor=test&type=AllFields

That seem to be the source of the problem : 
https://github.com/vufind-org/vufind/pull/1065

Vufind/Summon extends now DefaultRecord and not SolrDefault
