### ISSUE TITLE
Coveranzeige Posters

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#674]
Bei der Poster-Sammlung rechnen wir wahrscheinlich immer damit, dass ein Bild zurückgeliefert wird. Das ist leider nicht immer der Fall, obwohl eine URL vorhanden ist.
Das sollte abgefangen und als Platzhalter das Icon für Bildmaterial verwendet werden.

Beispiele siehe: https://www.swissbib.ch/Search/Results?lookfor=&type=AllFields&filter%5B%5D=%7Eunion%3A%22CCSA%22&limit=20

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[vufind] Coveranzeige Posters](https://trello.com/c/IrhNo0lM/373-vufind-coveranzeige-posters)

**Comment by liowalter** [comment]
From the 90'000 Posters, 14'000 are unavailable.

- Checking if there is a real picture in solrmarc.php is feasible, but that slows down the display too much.
- Unfortunately the BN cannot deliver right now a rule to know if there is an image or not
- One option would be to create a custom cover deliverer (as amazon) that would deliver the poster image after displaying the resultlist (via the CoverController). But I am not sure that the time investment is worth it for 14'000 records.

I would rather let it like that for now.

**Comment by guenterh** [comment]
I agree Lionel, we shouldn't make it perfect for a subset that isn't too big.
For me - the customCoverController sounds like an elegant idea. My understanding of the flow of sequence is:
- The specialized CoverCotroller for POSTER pictures is configured in the same way as all the other VuFind image providers
- it would be called at the first place (at least before the standard one)
- it needs to recognize if it is "responsible" for this kind of image
- if yes, it should try to make the call and if it gets a no resource found response (should be available with the adaptation we have done some weeks ago) it hands over to the default image provider (Amazon)
- I think the effort shouldn't be big because I guess (not sure) we can use most of the code already available and use it in a way compatible with the standard VuFind cover mechanism.

Shall we discuss it at the next scrum meeting?

**Comment by liowalter** [comment]
Solved by the NB thanks a new oai set <code>chccsa2</code>
